-- ============================================================
--  FakeLive Pro — seed_avatars.sql
--  Siembra lc_avatars con retratos reales
--  Fuentes: randomuser.me (99F + 99M) + pravatar.cc (35F + 35M)
--  Total: ~268 avatares de personas reales
--
--  Ejecutar en:
--  https://supabase.com/dashboard/project/ydpnzcspwlwfcxzizqct
--  → SQL Editor → New query → pegar esto → Run
--
--  IDEMPOTENTE: INSERT con WHERE NOT IN (no necesita UNIQUE constraint)
-- ============================================================

-- ── Mujeres randomuser.me — Colombia ─────────────────────
-- young (18-30): indices 1-33
-- adult (31-45): indices 34-66
-- middle (46+):  indices 67-99
INSERT INTO public.lc_avatars (url, gender, age_group, country, style)
SELECT v.url, v.gender, v.age_group, v.country, v.style
FROM (VALUES
  ('https://randomuser.me/api/portraits/women/1.jpg',  'female','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/2.jpg',  'female','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/3.jpg',  'female','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/4.jpg',  'female','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/5.jpg',  'female','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/6.jpg',  'female','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/7.jpg',  'female','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/8.jpg',  'female','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/9.jpg',  'female','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/10.jpg', 'female','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/11.jpg', 'female','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/12.jpg', 'female','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/13.jpg', 'female','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/14.jpg', 'female','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/15.jpg', 'female','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/16.jpg', 'female','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/17.jpg', 'female','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/18.jpg', 'female','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/19.jpg', 'female','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/20.jpg', 'female','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/21.jpg', 'female','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/22.jpg', 'female','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/23.jpg', 'female','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/24.jpg', 'female','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/25.jpg', 'female','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/26.jpg', 'female','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/27.jpg', 'female','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/28.jpg', 'female','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/29.jpg', 'female','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/30.jpg', 'female','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/31.jpg', 'female','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/32.jpg', 'female','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/33.jpg', 'female','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/34.jpg', 'female','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/35.jpg', 'female','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/36.jpg', 'female','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/37.jpg', 'female','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/38.jpg', 'female','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/39.jpg', 'female','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/40.jpg', 'female','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/41.jpg', 'female','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/42.jpg', 'female','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/43.jpg', 'female','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/44.jpg', 'female','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/45.jpg', 'female','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/46.jpg', 'female','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/47.jpg', 'female','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/48.jpg', 'female','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/49.jpg', 'female','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/50.jpg', 'female','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/51.jpg', 'female','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/52.jpg', 'female','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/53.jpg', 'female','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/54.jpg', 'female','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/55.jpg', 'female','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/56.jpg', 'female','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/57.jpg', 'female','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/58.jpg', 'female','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/59.jpg', 'female','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/60.jpg', 'female','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/61.jpg', 'female','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/62.jpg', 'female','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/63.jpg', 'female','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/64.jpg', 'female','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/65.jpg', 'female','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/66.jpg', 'female','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/67.jpg', 'female','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/68.jpg', 'female','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/69.jpg', 'female','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/70.jpg', 'female','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/71.jpg', 'female','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/72.jpg', 'female','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/73.jpg', 'female','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/74.jpg', 'female','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/75.jpg', 'female','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/76.jpg', 'female','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/77.jpg', 'female','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/78.jpg', 'female','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/79.jpg', 'female','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/80.jpg', 'female','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/81.jpg', 'female','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/82.jpg', 'female','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/83.jpg', 'female','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/84.jpg', 'female','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/85.jpg', 'female','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/86.jpg', 'female','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/87.jpg', 'female','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/88.jpg', 'female','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/89.jpg', 'female','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/90.jpg', 'female','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/91.jpg', 'female','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/92.jpg', 'female','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/93.jpg', 'female','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/94.jpg', 'female','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/95.jpg', 'female','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/96.jpg', 'female','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/97.jpg', 'female','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/98.jpg', 'female','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/women/99.jpg', 'female','middle','Colombia','photo')
) AS v(url, gender, age_group, country, style)
WHERE v.url NOT IN (SELECT url FROM public.lc_avatars);

-- ── Hombres randomuser.me — Colombia ─────────────────────
INSERT INTO public.lc_avatars (url, gender, age_group, country, style)
SELECT v.url, v.gender, v.age_group, v.country, v.style
FROM (VALUES
  ('https://randomuser.me/api/portraits/men/1.jpg',  'male','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/2.jpg',  'male','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/3.jpg',  'male','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/4.jpg',  'male','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/5.jpg',  'male','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/6.jpg',  'male','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/7.jpg',  'male','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/8.jpg',  'male','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/9.jpg',  'male','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/10.jpg', 'male','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/11.jpg', 'male','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/12.jpg', 'male','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/13.jpg', 'male','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/14.jpg', 'male','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/15.jpg', 'male','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/16.jpg', 'male','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/17.jpg', 'male','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/18.jpg', 'male','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/19.jpg', 'male','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/20.jpg', 'male','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/21.jpg', 'male','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/22.jpg', 'male','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/23.jpg', 'male','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/24.jpg', 'male','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/25.jpg', 'male','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/26.jpg', 'male','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/27.jpg', 'male','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/28.jpg', 'male','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/29.jpg', 'male','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/30.jpg', 'male','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/31.jpg', 'male','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/32.jpg', 'male','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/33.jpg', 'male','young', 'Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/34.jpg', 'male','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/35.jpg', 'male','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/36.jpg', 'male','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/37.jpg', 'male','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/38.jpg', 'male','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/39.jpg', 'male','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/40.jpg', 'male','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/41.jpg', 'male','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/42.jpg', 'male','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/43.jpg', 'male','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/44.jpg', 'male','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/45.jpg', 'male','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/46.jpg', 'male','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/47.jpg', 'male','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/48.jpg', 'male','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/49.jpg', 'male','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/50.jpg', 'male','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/51.jpg', 'male','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/52.jpg', 'male','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/53.jpg', 'male','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/54.jpg', 'male','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/55.jpg', 'male','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/56.jpg', 'male','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/57.jpg', 'male','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/58.jpg', 'male','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/59.jpg', 'male','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/60.jpg', 'male','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/61.jpg', 'male','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/62.jpg', 'male','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/63.jpg', 'male','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/64.jpg', 'male','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/65.jpg', 'male','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/66.jpg', 'male','adult','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/67.jpg', 'male','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/68.jpg', 'male','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/69.jpg', 'male','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/70.jpg', 'male','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/71.jpg', 'male','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/72.jpg', 'male','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/73.jpg', 'male','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/74.jpg', 'male','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/75.jpg', 'male','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/76.jpg', 'male','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/77.jpg', 'male','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/78.jpg', 'male','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/79.jpg', 'male','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/80.jpg', 'male','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/81.jpg', 'male','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/82.jpg', 'male','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/83.jpg', 'male','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/84.jpg', 'male','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/85.jpg', 'male','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/86.jpg', 'male','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/87.jpg', 'male','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/88.jpg', 'male','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/89.jpg', 'male','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/90.jpg', 'male','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/91.jpg', 'male','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/92.jpg', 'male','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/93.jpg', 'male','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/94.jpg', 'male','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/95.jpg', 'male','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/96.jpg', 'male','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/97.jpg', 'male','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/98.jpg', 'male','middle','Colombia','photo'),
  ('https://randomuser.me/api/portraits/men/99.jpg', 'male','middle','Colombia','photo')
) AS v(url, gender, age_group, country, style)
WHERE v.url NOT IN (SELECT url FROM public.lc_avatars);

-- ── Mujeres pravatar.cc — otros países ────────────────────
-- pravatar.cc: 70 retratos reales, índices 1-70
-- Asignados a Venezuela, Ecuador, México, Argentina, Perú, Chile
INSERT INTO public.lc_avatars (url, gender, age_group, country, style)
SELECT v.url, v.gender, v.age_group, v.country, v.style
FROM (VALUES
  ('https://i.pravatar.cc/100?img=1',  'female','young', 'Venezuela','photo'),
  ('https://i.pravatar.cc/100?img=2',  'female','young', 'Venezuela','photo'),
  ('https://i.pravatar.cc/100?img=3',  'female','young', 'Venezuela','photo'),
  ('https://i.pravatar.cc/100?img=4',  'female','adult','Venezuela','photo'),
  ('https://i.pravatar.cc/100?img=5',  'female','adult','Venezuela','photo'),
  ('https://i.pravatar.cc/100?img=6',  'female','adult','Venezuela','photo'),
  ('https://i.pravatar.cc/100?img=7',  'female','young', 'Ecuador',  'photo'),
  ('https://i.pravatar.cc/100?img=8',  'female','young', 'Ecuador',  'photo'),
  ('https://i.pravatar.cc/100?img=9',  'female','adult','Ecuador',  'photo'),
  ('https://i.pravatar.cc/100?img=10', 'female','adult','Ecuador',  'photo'),
  ('https://i.pravatar.cc/100?img=11', 'female','young', 'México',   'photo'),
  ('https://i.pravatar.cc/100?img=12', 'female','young', 'México',   'photo'),
  ('https://i.pravatar.cc/100?img=13', 'female','adult','México',   'photo'),
  ('https://i.pravatar.cc/100?img=14', 'female','adult','México',   'photo'),
  ('https://i.pravatar.cc/100?img=15', 'female','middle','México',  'photo'),
  ('https://i.pravatar.cc/100?img=16', 'female','young', 'Argentina','photo'),
  ('https://i.pravatar.cc/100?img=17', 'female','young', 'Argentina','photo'),
  ('https://i.pravatar.cc/100?img=18', 'female','adult','Argentina','photo'),
  ('https://i.pravatar.cc/100?img=19', 'female','adult','Argentina','photo'),
  ('https://i.pravatar.cc/100?img=20', 'female','middle','Argentina','photo'),
  ('https://i.pravatar.cc/100?img=21', 'female','young', 'Perú',     'photo'),
  ('https://i.pravatar.cc/100?img=22', 'female','adult','Perú',     'photo'),
  ('https://i.pravatar.cc/100?img=23', 'female','young', 'Chile',    'photo'),
  ('https://i.pravatar.cc/100?img=24', 'female','adult','Chile',    'photo'),
  ('https://i.pravatar.cc/100?img=25', 'female','middle','Chile',   'photo'),
  ('https://i.pravatar.cc/100?img=26', 'female','young', 'Colombia', 'photo'),
  ('https://i.pravatar.cc/100?img=27', 'female','adult','Colombia', 'photo'),
  ('https://i.pravatar.cc/100?img=28', 'female','middle','Colombia','photo'),
  ('https://i.pravatar.cc/100?img=29', 'female','young', 'Colombia', 'photo'),
  ('https://i.pravatar.cc/100?img=30', 'female','adult','Colombia', 'photo'),
  ('https://i.pravatar.cc/100?img=31', 'female','young', 'Venezuela','photo'),
  ('https://i.pravatar.cc/100?img=32', 'female','adult','Venezuela','photo'),
  ('https://i.pravatar.cc/100?img=33', 'female','middle','Ecuador', 'photo'),
  ('https://i.pravatar.cc/100?img=34', 'female','young', 'México',   'photo'),
  ('https://i.pravatar.cc/100?img=35', 'female','adult','Argentina','photo')
) AS v(url, gender, age_group, country, style)
WHERE v.url NOT IN (SELECT url FROM public.lc_avatars);

-- ── Hombres pravatar.cc — otros países ───────────────────
INSERT INTO public.lc_avatars (url, gender, age_group, country, style)
SELECT v.url, v.gender, v.age_group, v.country, v.style
FROM (VALUES
  ('https://i.pravatar.cc/100?img=36', 'male','young', 'Venezuela','photo'),
  ('https://i.pravatar.cc/100?img=37', 'male','young', 'Venezuela','photo'),
  ('https://i.pravatar.cc/100?img=38', 'male','adult','Venezuela','photo'),
  ('https://i.pravatar.cc/100?img=39', 'male','adult','Venezuela','photo'),
  ('https://i.pravatar.cc/100?img=40', 'male','young', 'Ecuador',  'photo'),
  ('https://i.pravatar.cc/100?img=41', 'male','young', 'Ecuador',  'photo'),
  ('https://i.pravatar.cc/100?img=42', 'male','adult','Ecuador',  'photo'),
  ('https://i.pravatar.cc/100?img=43', 'male','adult','Ecuador',  'photo'),
  ('https://i.pravatar.cc/100?img=44', 'male','young', 'México',   'photo'),
  ('https://i.pravatar.cc/100?img=45', 'male','young', 'México',   'photo'),
  ('https://i.pravatar.cc/100?img=46', 'male','adult','México',   'photo'),
  ('https://i.pravatar.cc/100?img=47', 'male','adult','México',   'photo'),
  ('https://i.pravatar.cc/100?img=48', 'male','middle','México',  'photo'),
  ('https://i.pravatar.cc/100?img=49', 'male','young', 'Argentina','photo'),
  ('https://i.pravatar.cc/100?img=50', 'male','young', 'Argentina','photo'),
  ('https://i.pravatar.cc/100?img=51', 'male','adult','Argentina','photo'),
  ('https://i.pravatar.cc/100?img=52', 'male','adult','Argentina','photo'),
  ('https://i.pravatar.cc/100?img=53', 'male','middle','Argentina','photo'),
  ('https://i.pravatar.cc/100?img=54', 'male','young', 'Perú',     'photo'),
  ('https://i.pravatar.cc/100?img=55', 'male','adult','Perú',     'photo'),
  ('https://i.pravatar.cc/100?img=56', 'male','middle','Perú',    'photo'),
  ('https://i.pravatar.cc/100?img=57', 'male','young', 'Chile',    'photo'),
  ('https://i.pravatar.cc/100?img=58', 'male','adult','Chile',    'photo'),
  ('https://i.pravatar.cc/100?img=59', 'male','middle','Chile',   'photo'),
  ('https://i.pravatar.cc/100?img=60', 'male','young', 'Colombia', 'photo'),
  ('https://i.pravatar.cc/100?img=61', 'male','adult','Colombia', 'photo'),
  ('https://i.pravatar.cc/100?img=62', 'male','middle','Colombia','photo'),
  ('https://i.pravatar.cc/100?img=63', 'male','young', 'Venezuela','photo'),
  ('https://i.pravatar.cc/100?img=64', 'male','adult','Ecuador',  'photo'),
  ('https://i.pravatar.cc/100?img=65', 'male','young', 'México',   'photo'),
  ('https://i.pravatar.cc/100?img=66', 'male','adult','Argentina','photo'),
  ('https://i.pravatar.cc/100?img=67', 'male','young', 'Perú',     'photo'),
  ('https://i.pravatar.cc/100?img=68', 'male','adult','Chile',    'photo'),
  ('https://i.pravatar.cc/100?img=69', 'male','young', 'Colombia', 'photo'),
  ('https://i.pravatar.cc/100?img=70', 'male','adult','Colombia', 'photo')
) AS v(url, gender, age_group, country, style)
WHERE v.url NOT IN (SELECT url FROM public.lc_avatars);

-- ── Verificar totales ─────────────────────────────────────
SELECT gender, age_group, country, COUNT(*) AS total
FROM public.lc_avatars
GROUP BY gender, age_group, country
ORDER BY country, gender, age_group;
